### PR TITLE
Scripts added to plugin package.json

### PR DESCRIPTION
**Pull request by derweili**
This PR is related to issue #224

### CODE REVIEW

**Comment by schlessera** [comment]
We need to document this somewhere as well. As the generated readme for the plugin is useless (only placeholder content), the best place is probably to add it to the command description here: https://github.com/wp-cli/scaffold-command/blob/v2.0.6/src/Scaffold_Command.php#L589-L606

**Comment by derweili** [comment]
I added the scripts to the command descriptions.

**Comment by swissspidy** [comment]
We should really use some more modern scripts there at some point.

**Comment by schlessera** [comment]
Related: #233

**Comment by schlessera** [comment]
I'm merging this now, knowing that the ultimate goal should be to modernize the tooling in general.

Having the scripts in place makes swapping the tooling out easier for people already relying on these scripts.

**Pull request merged**
