### PR TITLE
add behat tests for install-wp-tests.sh

### PR DESCRIPTION
**Pull request by miya0001**
Add behat tests for `templates/install-wp-tests.sh`.

There are 3 scenarios.

* Usage should be displayed.
* Installs latest version of the WordPress.
* Installs WordPress 3.7.

### CODE REVIEW

**Comment by miya0001** [comment]
Related: https://github.com/wp-cli/scaffold-command/pull/35

**Comment by miya0001** [comment]
Ah, I want to improve those tests to run `phpunit`.

**Comment by danielbachhuber** [comment]
Great work on this @miya0001 — thanks for taking the initiative.

**Comment by miya0001** [comment]
I finished to develop it.

There are 3 scenarios:

* Run `install-wp-tests.sh` with `latest`, then check the files should exist as expected and run `phpunit`.
* Run `install-wp-tests.sh` with `trunk`, then check the files should exist as expected and run `phpunit`.
* Run `install-wp-tests.sh` with `3.7`, then check the files should exist as expected. But `phpunit` isn't executed because before older version of WordPress or WP_UnitTestCase does't have compatible with PHP.

**Pull request merged**
