### PR TITLE
CS: Show progress when invoking phpcs

### LINKED ISSUE #62: Add 'p' arg to show PHPCS progress
Adding the `p` argument to `phpcs.xml.dist` allows progress to be shown when invoking `phpcs`, which gives confidence to the user that something is happening.

Change:
```xml
	<!-- Show sniff codes in all reports -->
	<arg value="s"/>
```

to:

```xml
	<!-- Show progress and sniff codes in all reports -->
	<arg value="ps"/>
```

### PR DESCRIPTION
**Pull request by GaryJones**
Displays the progress meter to help identify that phpcs is working.

Closes #62.

### CODE REVIEW

**Comment by GaryJones** [comment]
I'm unsure how that build failure is related to the change I made.

**Comment by danielbachhuber** [comment]
@miya0001 ^

**Comment by wojsmol** [comment]
@danielbachhuber trunk is now in beta1 state. I m test we expecting alpha state.

**Comment by danielbachhuber** [comment]
> Trunk is now in beta1 state. I m test we expecting alpha state, ref

Correct. See conversation in https://github.com/wp-cli/scaffold-command/pull/61#discussion_r143703835

**Comment by miya0001** [comment]
@GaryJones Please merge `master` into this branch to fix build failure. Thanks 😊

**Comment by danielbachhuber** [comment]
> Please merge `master` into this branch to fix build failure.

I've done so.

@miya0001 Btw, for small things like merging master or making small changes, it's easier for you to make the change directly:

```
$ cd vendor/wp-cli/scaffold-command
$ git pull origin master
$ git remote add garyjones https://github.com/GaryJones/scaffold-command.git
$ git fetch garyjones
$ git checkout cs-phpcs-progress-meter
$ git merge master
$ git push
```

**Comment by miya0001** [comment]
@danielbachhuber Thanks 😊

**Pull request merged**
