### PR TITLE
add rule in pluralize() 

### PR DESCRIPTION
**Pull request by Umangvaghela**
add rule in pluralize() in Scaffold_Command.php

### CODE REVIEW

**Comment by miya0001** [comment]
Hi @Umangvaghela 

Thanks for PR. 😄 

Where did you get those information? Are there any reference or so?
We want to see them.

**Comment by Umangvaghela** [comment]
Hi @miya0001 

I have worked on two months ago at this point in another framework.When I see this thing in the function then I decided to add this three rule.It is also useful in pluralization.I will send reference link as soon as possible.

**Comment by Umangvaghela** [comment]
@miya0001 

Reference link:
 http://kuwamoto.org/2007/12/17/improved-pluralizing-in-php-actionscript-and-ror/

**Comment by miya0001** [comment]
We are having discussion at #44

**Comment by miya0001** [comment]
See https://github.com/wp-cli/scaffold-command/pull/44#issuecomment-324383822

@Umangvaghela Thanks!

**Pull request closed without merging**
