### PR TITLE
Include `--ignore-externals` when running svn co

### PR DESCRIPTION
**Pull request by danielbachhuber**
The SVN externals aren't necessary in this context because we only need the test suite data

### CODE REVIEW

**Comment by esquinas** [comment]
Did you tried adding `--ignore-externals` just to the second `svn co` line and see if travis-ci passes?

**Comment by danielbachhuber** [comment]
> Did you tried adding `--ignore-externals` just to the second `svn co` line and see if travis-ci passes?

I didn't, no.

**Comment by schlessera** [comment]
Test failures seem to be another SSL issue with the Travis build. I'll look into it.

**Comment by schlessera** [comment]
Related: https://meta.trac.wordpress.org/ticket/4869

**Comment by schlessera** [comment]
Thanks for the PR, @danielbachhuber!

If you merge latest `master`, the tests should pass now.

**Comment by danielbachhuber** [comment]
@schlessera Updated!

**Pull request merged**
