### PR TITLE
Add one more potential path for templates

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes https://github.com/wp-cli/extension-command/issues/9

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera To test:

```
git clone git@github.com:wp-cli/extension-command.git
cd extension-command
composer install --no-dev
composer require wp-cli/wp-cli:dev-master
export WP_CLI_BIN_DIR=$(pwd)/vendor/bin
```

I'd have to say this type of bug is quite annoying though. Definitely open to ideas on how we can improve.

**Comment by schlessera** [comment]
I don't think that's a good approach to fix this bug.

The bug happens because you use the framework rootfolder to locate a command subfolder. As the command has been split out, it can move around independently of the framework.

So, I would recommend to locate the command subfolder based on the command rootfolder (or a known subfolder of the command), instead of the independent framework rootfolder.

Something like: 
```
$template_path = dirname( __DIR__ ) . '/templates/' . $template;
```

**Comment by danielbachhuber** [comment]
> The bug happens because you use the framework rootfolder to locate a command subfolder. As the command has been split out, it can move around independently of the framework.

It's still dependent on `WP_CLI_ROOT`, though, to produce the proper path in a Phar.

> So, I would recommend to locate the command subfolder based on the command rootfolder (or a known subfolder of the command), instead of the independent framework rootfolder.

This doesn't work inside the Phar.

**Comment by danielbachhuber** [comment]
Related https://github.com/wp-cli/wp-cli/issues/3987

**Comment by schlessera** [comment]
I ran some tests, and I found a way to get the command path from within a phar. The basic code is this:
```
$command_root = str_replace( 'phar://' . getcwd() . '/', 'phar://', __DIR__ );
$template_path = dirname( $command_root ) . '/templates/' . $template;
```

This basically uses the `__DIR__` constant (as reference to the command location) and removes the current working dir from it to reduce it to the phar portion.

What do you think? Is this something we can use?

**Comment by danielbachhuber** [comment]
Closing in favor of #12

**Pull request closed without merging**
