### PR TITLE
Revert "Added comma after last array item"

### PR DESCRIPTION
**Pull request by Sidsector9**
Reverts wp-cli/scaffold-command#46

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@Sidsector9 Why are you reverting this?

**Comment by Sidsector9** [comment]
@danielbachhuber I merged it before reading the message by @miya0001 on slack, he said that we have to wait till a milestone is assigned to this PR.

**Comment by danielbachhuber** [comment]
> he said that we have to wait till a milestone is assigned to this PR.

Yes, I did that:

image

Please read/comment on https://github.com/wp-cli/handbook/pull/127 so we can better document the process.

**Comment by schlessera** [comment]
@Sidsector9 I'll remove the milestone again that you've added here. This was not merged, so it should not be part of the milestone.

We'll later use the milestone to check what went into a specific release to write the release notes.

**Comment by Sidsector9** [comment]
@schlessera alright

**Pull request closed without merging**
