### PR TITLE
Enhance pluralization

### PR DESCRIPTION
**Pull request by fumikito**
Relates to #48, added Doctrine Inflector class and replaced exiting method `pluralize` .

I considered adding unit test, but didn't add. Because `pluralize` is just an alias for Inflector's method  which is [fully tested](https://github.com/doctrine/inflector/blob/master/tests/Doctrine/Tests/Common/Inflector/InflectorTest.php).

### CODE REVIEW

**Comment by miya0001** [comment]
Thanks for pull-request @fumikito.

* I guess the name space of the `Inflector` should be like `WP_CLI\Inflector` instead of `Doctrine\Common\Inflector`.
* We need to add props to original project of this library like https://github.com/WordPress/WordPress/blob/5eb452d15b4d99fcd19bc97dd53876547c7b2655/wp-includes/class-phpmailer.php#L2-L18
* Do we need unit test?

@wp-cli/committers Any thoughts?

**Comment by gitlost** [comment]
> I guess the name space of the `Inflector` should be like `WP_CLI\Inflector`

That sounds good (and necessary).

> We need to add props to original project

I'm not sure why they did that in core, looks OTT. The `Doctrine\Inflector` project is a stand-alone repo so I'd have thought what's in the class now is enough.

> Do we need unit test?

I see no real need, as @fumikito says.

**Comment by schlessera** [comment]
> I'm not sure why they did that in core, looks OTT.

The PHPMailer license bit was probably part of the original PHPMailer source code and just copied over.

In our case, the existing license text should be sufficient.

I would like to see 1 additional feature test that uses one of the inflections that were not part of the previous code. This will allow us to detect regressions where we're relying on an old function implmentation.

**Comment by gitlost** [comment]
Shouldn't the namespace be changed as @miya0001 suggested, in case of clashing with user inclusion?

**Comment by danielbachhuber** [comment]
> Shouldn't the namespace be changed as @miya0001 suggested, in case of clashing with user inclusion?

Yes, good catch. Want to submit a PR?

**Comment by miya0001** [comment]
Ah, I will. :)

**Pull request merged**
